### ISSUE TITLE
Tallo forest allometry data

### ISSUE THREAD

**Issue by i-c-grant** [Cidree/forestdata#1]
Nice package, thanks for putting this together! The Tallo dataset of field measurements of forest allometry (Jucker et al., 2022) could be a useful addition (https://github.com/selva-lab-repo/TALLO).

**Comment by Cidree** [comment]
Thank you @i-c-grant ! Very interesting dataset.
I will add it to the next release.

**Comment by Cidree** [comment]
TALLO database has been added to the development version. I will push the changes throughout the weekend, and they will be added to the next version.
