### ISSUE TITLE
Higher resolution canopy height

### ISSUE THREAD

**Issue by Wycology** [Cidree/forestdata#2]
You could add a higher resolution canopy height (1 m). https://gee-community-catalog.org/projects/meta_trees/

**Comment by Cidree** [comment]
That would be great! However, I found some issues when trying to access the data through R. Do you have any idea of how to do it @Wycology ?

So far, I used the `aws.s3` package to access the data. However, it looks like the data I am getting is something different:

```r
## Load packages
library(aws.s3)
library(terra)

# Specify the bucket and the prefix (path inside the bucket)
bucket <- "dataforgood-fb-data"
prefix <- "forests/v1/alsgedi_global_v6_float/"

# List the files in the S3 bucket (without authentication)
files <- get_bucket(
    bucket = bucket, 
    prefix = prefix, 
    region = "us-east-1"
)

# Print the file names
print(files)

# Download a specific file (replace with actual file name)
s3_file <- "forests/v1/alsgedi_global_v6_float/chm/003012330.tif"

# Save the file locally
out_file <- tempfile(fileext = ".tif")
save_object(
    object = s3_file, 
    bucket = bucket, 
    file   = out_file, 
    region = "us-east-1"
)

# Read it into R and visualize
rast(out_file) |> plot()
```

![image](https://github.com/user-attachments/assets/58354c4b-3d2f-4cba-888c-5aec1eb50149)

**Comment by Wycology** [comment]
Your code is correct.
Note that the canopy heights are given as integer values and could be that the file you picked coincided with a relatively flat surface.

I tried a different file in the bucket and got expected canopy height values.
s3_file <- "forests/v1/alsgedi_global_v6_float/chm/002333230.tif"
![image](https://github.com/user-attachments/assets/befcc19e-8c66-4aa0-80e4-24f69d2e91c3)

**Comment by Cidree** [comment]
Hei @Wycology ! Sorry for the delay, I had a lot of work last weeks.
I have this function working on the dev branch. 

Tomorrow I hope I will finish some changes, and release 0.2.0
